apiVersion: v1
kind: Secret
metadata:
  name: {{ include "qaq.fullname" . }}
  labels:
    {{- include "qaq.labels" . | nindent 4 }}
data:
  FEISHU_APP_ID: {{ .Values.secret.feishu.FEISHU_APP_ID | b64enc | quote }}
  FEISHU_APP_SECRET: {{ .Values.secret.feishu.FEISHU_APP_SECRET | b64enc | quote }}
  FEISHU_ENCRYPT_KEY: {{ .Values.secret.feishu.FEISHU_ENCRYPT_KEY | b64enc | quote }}
  FEISHU_VERIFICATION_TOKEN: {{ .Values.secret.feishu.FEISHU_VERIFICATION_TOKEN | b64enc | quote }}
  MYSQL_SERVER: {{ .Values.secret.mysql.MYSQL_SERVER | b64enc | quote }}
  MYSQL_PORT: {{ .Values.secret.mysql.MYSQL_PORT | b64enc | quote }}
  MYSQL_USER: {{ .Values.secret.mysql.MYSQL_USER | b64enc | quote }}
  MYSQL_PASSWORD: {{ .Values.secret.mysql.MYSQL_PASSWORD | b64enc | quote }}
  RSA_PUBLICKEY: {{ .Values.secret.rsa.RSA_PUBLICKEY | b64enc | quote }}
  RSA_PRIVATEKEY: {{ .Values.secret.rsa.RSA_PRIVATEKEY | b64enc | quote }}
  QAQ_ADMIN: {{ .Values.secret.QAQ_ADMIN | b64enc | quote }}
  QAQ_HOST: {{ .Values.secret.QAQ_HOST | b64enc | quote }}