apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qaq.fullname" . }}-{{ .Values.gateway.role }}
  labels:
    {{- include "qaq.labels" . | nindent 4 }}
data:
  application.yaml: |
    logging:
      level:
        root: WARN
        org.springframework.web: INFO
        com.qaq.gateway: INFO
    spring:
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
