apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "qaq.fullname" . }}-{{ .Values.gateway.role }}
  labels:
    {{- include "qaq.labels" . | nindent 4 }}
    {{- with .Values.gateway.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/name: {{ template "qaq.name" . }}-{{ .Values.gateway.role }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag }}
    app.kubernetes.io/component: {{ .Values.gateway.role }}
  annotations:
    {{- with .Values.gateway.annotations }}
    {{ toYaml . | nindent 8 }}
    {{- end }}
spec:
  replicas: {{ .Values.gateway.scaling.replicas }}
  revisionHistoryLimit: {{ .Values.gateway.scaling.revisionHistoryLimit }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      {{- include "qaq.matchLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "qaq.labels" . | nindent 8 }}
        {{- with .Values.gateway.labels }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        app.kubernetes.io/name: {{ template "qaq.name" . }}-{{ .Values.gateway.role }}
        app.kubernetes.io/version: {{ .Values.gateway.image.tag }}
        app.kubernetes.io/component: {{ .Values.gateway.role }}
      annotations:
        {{- with .Values.gateway.annotations }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ template "qaq.name" . }}-{{ .Values.gateway.role }}
          image: "{{ .Values.gateway.image.repository }}:{{ .Values.gateway.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          env:
            - name: RSA_PUBLICKEY
              valueFrom:
                secretKeyRef:
                  name:  {{ include "qaq.fullname" . }}
                  key: RSA_PUBLICKEY
          {{- with .Values.gateway.containers.env }}
          {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.gateway.containers.ports }}
          ports:
          {{ toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - mountPath: /application.yaml
              name: application
              subPath: application.yaml
          {{- with .Values.gateway.containers.volumeMounts }}
          {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.app.security.containerSecurityContext }}
          securityContext:
          {{ toYaml . | nindent 12 }}
          {{- end }}

          {{- with .Values.gateway.containers.resources }}
          resources:
          {{ toYaml . | nindent 12 }}
          {{- end }}

      {{- with .Values.app.image.pullSecrets }}
      imagePullSecrets:
      {{- range . }}
        - name: {{ . }}
      {{- end }}
      {{- end }}

      automountServiceAccountToken: {{ .Values.gateway.automountServiceAccountToken }}

      {{- with .Values.app.security.securityContext }}
      securityContext:
      {{ toYaml . | nindent 8 }}
      {{- end }}

      volumes:
        - name: application
          configMap:
            name:  {{ include "qaq.fullname" . }}-{{ .Values.gateway.role }}
      {{- with .Values.gateway.volumes }}
      {{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.app.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}

      {{- if or .Values.gateway.nodeSelector .Values.app.scheduling.nodeSelector }}
      nodeSelector:
      {{- with .Values.gateway.nodeSelector }}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.app.scheduling.nodeSelector }}
      {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- end }}

      {{- with .Values.app.tolerations }}
      tolerations:
      {{ toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.app.affinity }}
      affinity:
      {{ toYaml . | nindent 8 }}
      {{- end }}

      serviceAccountName: {{ template "qaq.fullname" . }}