{{- if and .Values.app.ingress.enabled }}

kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  labels:
    {{- include "qaq.labels" . | nindent 4 }}
    {{- with .Values.app.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.app.ingress.useDefaultAnnotations }}
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    {{- end }}
    {{- with .Values.app.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  name: {{ template "qaq.name" . }}
spec:
  {{- if not .Values.app.ingress.useDefaultIngressClass }}
  ingressClassName: {{ .Values.app.ingress.ingressClassName }}
  {{- end }}
  {{- if and .Values.app.ingress.hosts .Values.app.ingress.tls.enabled }}
  tls:
    - hosts:
      {{- toYaml .Values.app.ingress.hosts | nindent 6 }}
      {{- if .Values.app.ingress.tls.secretName }}
      secretName: {{ .Values.app.ingress.tls.secretName }}
      {{- else }}
      secretName: {{ template "qaq.app.ingress.secret.name" . }}
      {{- end }}
  {{- end }}
  rules:
    {{- if .Values.app.ingress.hosts }}
    {{- range $host := .Values.app.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: {{ $.Values.app.ingress.pathType }}
            backend:
              service:
                name: {{ template "qaq.fullname" . }}-{{ .Values.uniauthweb.role }}
                port:
                  number: 80
          - path: /api/
            pathType: {{ $.Values.app.ingress.pathType }}
            backend:
              service:
                name: {{ template "qaq.fullname" . }}-{{ .Values.gateway.role }}
                port:
                  number: 80
          - path: /web/
            pathType: {{ $.Values.app.ingress.pathType }}
            backend:
              service:
                name: {{ template "qaq.fullname" . }}-{{ .Values.uniauth.role }}
                port:
                  number: 80
        {{- end }}
    {{- end }}
{{- end }}