apiVersion: v1
kind: Service
metadata:
  name: {{ include "qaq.fullname" . }}-{{ .Values.gateway.role }}
  labels:
    {{- include "qaq.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qaq.selectorLabels" . | nindent 4 }}
