kind: Service
apiVersion: v1
metadata:
  labels:
    {{- include "qaq.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "qaq.name" . }}-{{ .Values.gateway.role }}
    app.kubernetes.io/version: {{ .Values.gateway.image.tag }}
    app.kubernetes.io/component: {{ .Values.gateway.role }}
  name: {{ template "qaq.fullname" . }}-{{ .Values.gateway.role }}
spec:
  ports:
    - name: {{ .Values.gateway.role }}
    {{- with (index .Values.gateway.containers.ports 0) }}
      port: {{ .containerPort }}
    {{- end }}
  selector:
    {{- include "qaq.matchLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ template "qaq.name" . }}-{{ .Values.gateway.role }}